inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - Gemfile

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 13
